# hosts/hypervisor/hardware-configuration.nix
# PLACEHOLDER: Generate actual hardware config on target machine with:
# nixos-generate-config --show-hardware-config > hosts/hypervisor/hardware-configuration.nix
{ ... }:
{
  # This is a placeholder file
  # On actual deployment, replace with machine-specific hardware config
  # Generated by nixos-generate-config
}
