name: Documentation

on: [merge_group, push, pull_request]

jobs:
  deploy:
    name: build and deploy doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - name: Create production theme
        run: |
          echo >> doc/book.toml
          echo 'theme="theme"' >> doc/book.toml
          mkdir doc/theme
          echo '<script defer data-domain="microvm-nix.github.io" src="https://p.spaceboyz.net/js/script.js"></script>' > doc/theme/head.hbs
          git add doc/theme
      - name: Build
        run: nix build .#doc
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
