name: "prebuilt-unstable"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * *' # runs daily at 00:00
  merge_group:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      if: github.ref == 'refs/heads/main'
      with:
        name: microvm
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: cachix/cachix-action@v16
      if: github.ref != 'refs/heads/main'
      with:
        name: microvm
    - run: nix build -L .#prebuilt --override-input nixpkgs github:nixos/nixpkgs/nixos-unstable
